### PR TITLE
use a tag for links

### PR DESCRIPTION
**Pull request by benschac**
good for accessibility and people like me using vimium in chrome

### CODE REVIEW

**Comment by benschac** [comment]
Current dependencies on/for this PR:
* master
  * **PR #1854** <a href="https://app.graphite.dev/github/pr/tamagui/tamagui/1854?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1855** <a href="https://app.graphite.dev/github/pr/tamagui/tamagui/1855?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/tamagui/tamagui/1855?utm_source=stack-comment).

**Comment by natew** [comment]
i think these actually cuase some hydration issues or warnings due to "a inside a", if i don't remember correctly, have you tested in dev/prod?

**Comment by benschac** [comment]
I assumed hydration error is because a new ssr build with updated a tag wasn’t done. I could be wrong will try with a yarn build

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by benschac** [comment]
Oh shoot an inside a makes sense. Weird a tags were picking up before tho

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
