### PR TITLE
fix(core): `selectable` not working on `<Text>` as expected

### LINKED ISSUE #1536: Creating selectable text
I am trying to create a selectable text component where the user is able to copy/paste/etc.

Consider the following
```js
// import { Text } from "react-native"; // this works!
// import { Text } from "tamagui"; // this doesn't work...

<Text selectable={true}>asdasd</Text>
```
Passing in `selectable` prop does not achieve same functionality when using Tamagui's `Text` component, however it works in React Native's component. Testing on Expo Go Android.

How should I implement selectable text using Tamagui's Text component?

### PR DESCRIPTION
**Pull request by alitnk**
Fixes #1536 Creating selectable text

### CODE REVIEW

**Comment by mphill** [comment]
FYI, It seems like all text is selectable by default now.  I had to explicitly disable it.

**Comment by natew** [comment]
Oh I thought that was the default but I guess it makes sense for native not to. I’ll make that change.

**Comment by mphill** [comment]
I agree, it's definitely not.  

I noticed this because the `onLongPress` gesture was getting very hard to trigger.  Setting this to false should resolve that issue too so long presses will work on buttons etc  better.

**Comment by natew** [comment]
Hm I don't see us setting selectable on Text at all

**Comment by mphill** [comment]
> Hm I don't see us setting selectable on Text at all

I didn't either when I looked at the source.  I can definitely say that setting selectable to false gets the desired behavior. Can this be the default false?

https://reactnative.dev/docs/text#selectable

The default should be false according to the docs.

**Pull request merged**
