### PR TITLE
fix turbo dev run expo

### PR DESCRIPTION
**Pull request by benschac**
currently `turbo run dev` doesn't run expo

change start to dev, turbo now runs expo

reproduction:
`turbo run dev` web and expo servers start

### CODE REVIEW

**Comment by benschac** [comment]
Current dependencies on/for this PR:
* master
  * **PR #1288** <a href="https://app.graphite.dev/github/pr/tamagui/tamagui/1288" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/tamagui/tamagui/1288?utm_source=stack-comment).

**Comment by benschac** [comment]
I don't have time to look into the ci for this one. Going to close.

**Comment by benschac** [comment]
everyone is getting this issue, reopening

**Comment by benschac** [comment]
> expo start is a terminal UI. Parallelizing it as part of the turborepo dev task means it won't run in an interactive terminal and will be mostly unusable - no way to use hotkeys, no QR code gets rendered.

I've just been using the same simulator with expo go on it after I initially get setup and it's working fine. You're right.

Value here was just having one command to get all dev clients running. I understand if this doesn't make sense for everyone, feel free to close.

**Comment by benschac** [comment]
this has been open for a minute: https://github.com/vercel/turbo/issues/1235 bummer that it's still an issue

**Comment by natew** [comment]
Closing but it was a nice idea, maybe can revisit in some way

**Pull request closed without merging**
