### PR TITLE
feat(group): new API using `reforest`

### PR DESCRIPTION
**Pull request by alitnk**

### CODE REVIEW

**Comment by alitnk** [comment]
This works but it has a regression when it's used with a `separator` (e.g. `<Group separator={<Separator/>} ...>`). Will need to find an alternative to `spacedChildren()` or rewrite it to work with `reforest`.

**Comment by natew** [comment]
@alitnk if you can figure out the separator stuff would be nice. Can we make this backwards compat? Or should we move to a new component like `Group` instead?

**Comment by alitnk** [comment]
Fixed the separator. Not sure how backward compatibility would work... maybe detect if children are `<XGroup.Item`s and make it behave differently and otherwise default to the old impl?

**Comment by alitnk** [comment]
Thinking out loud here, I can think of a few options:
- Check if the first child is <XGroup.Item and use the new implementation if that's the case
- A prop to opt-in to the new implementation for now and gradually remove the old one and just move to that in v2 maybe... like `<XGroup itemChildren><XGroup.Item>...</XGroup.Item></XGroup>`
- Create a separate Group component, so no backward compatibility.
- Apply the old impl styles only on non-`XGroup.Item` components. will have to try this one out...

**Comment by alitnk** [comment]
Last one seems to work, will push it in a bit.

**Comment by alitnk** [comment]
Still, this doesn't seem to fix #701 - border radius issue with custom button still happening in the `site` app but not in `sandbox`.

**Comment by alitnk** [comment]
Found a regression - working on it...

**Comment by natew** [comment]
Wrote in discord, seeing SSR doubling:

https://user-images.githubusercontent.com/12100/221380605-cc842567-d7bf-4824-bdf6-c9a221893df3.mp4

also it doesn't seem to fall back to the old behavior if you don't use .Item, we could do that by having .Item look for context and call a callback to say "i'm mounted" and then the parent can switch the mode

**Pull request closed without merging**
