### PR TITLE
feat(Form): create @tamagui/form and add Form.Trigger #498

### PR DESCRIPTION
**Pull request by lobor**
see #498

### CODE REVIEW

**Comment by natew** [comment]
Looks like a great start that we can iterate on. Docs page subtitle needs fixing.

Wondering how we should work with `type="submit"`. Typically on web a Button with type="submit" will send the onSubmit event. It's possible we could make this work but we'd have to hook into Button, but that wouldn't be too bad. But may need Yet Another New Package :)

Just figure since we're here may as well do that.

There's also the BubbleInput a variety of inputs use, not sure if we want to do anything there.

**Comment by lobor** [comment]
ok, I'll edit that for the documentation.

For the web it might be necessary to have a condition in order to use type="submit" automatically, and use the context on the native. The problem with submit is that any other button with submit can submit the form, my dev's idea was to block that.

What exactly is BubbleInput?

**Comment by natew** [comment]
Something that Radix does https://github.com/tamagui/tamagui/blob/9658f5e3e1964d2bcee3494a25f33e5f0c142619/packages/switch/src/Switch.tsx#L230, web only thing, from what I can tell it just sends a normal input check event so I guess this should just work?

**Comment by natew** [comment]
If you can fix conflicts this should be good for release :)

**Comment by lobor** [comment]
it's fix

**Comment by lobor** [comment]
i fixed conflitct

**Comment by lobor** [comment]
@natew i resolve conflict
When do you think that PR will be merged ?

**Comment by natew** [comment]
Made some cleanups and merged!

**Comment by natew** [comment]
Thanks for this 🙏

**Pull request closed without merging**
