### PR TITLE
fix(core:types): variants tokens

### PR DESCRIPTION
**Pull request by TheEhsanSarshar**

### CODE REVIEW

**Comment by arekkubaczkowski** [comment]
@natew  @TheEhsanSarshar I assume that wasn't correct approach, however can we expect other/better solution?

**Comment by arekkubaczkowski** [comment]
By the way, guys, you're doing a really great job, and I truly appreciate it! Someday, I'm going to delve into the implementation details so I can help make this library even better 🤞

**Comment by TheEhsanSarshar** [comment]
oh, awesome that would be great! thanks ❤️
btw some changes to fix issue in landed, let me know if that fixed this issue

**Comment by arekkubaczkowski** [comment]
@TheEhsanSarshar I am still driving this issue, in which version this was supposed to be fixed?

**Comment by natew** [comment]
I did merge a different fix, can you get me a reproduction for what you're seeing?

**Comment by arekkubaczkowski** [comment]
@natew 

https://github.com/tamagui/tamagui/issues/2300

There is an issue reported already

**Comment by arekkubaczkowski** [comment]
In the latest version tokens are properly prefixed already but unfortunately suggesting still doesn't for for inline way.

@natew 
Screenshot 2024-03-13 at 15 48 52

**Pull request closed without merging**
