### PR TITLE
fix(tag prop): tag ignored when there is animation prop

### LINKED ISSUE #1985: Using `tag` on an element with `animation` is ignored
### Current Behavior

If you set both `tag` and `animation` props on an element, the `tag` will completely be ignored (tested with both CSS and Moti driver).

### Expected Behavior

The proper `tag` should still be used when animating

### Tamagui Version

```markdown
1.79.12
```

### Platform (Web, iOS, Android)

```markdown
web
```

### Reproduction

```tsx
import { View } from '@tamagui/core'

export const Sandbox = () => {
  return (
    // Inspect this in browser, and you'll see that a `div` is rendered instead of a `button`
    <View
      tag="button"
      animation="bouncy"
      height="$4"
      width="$4"
      backgroundColor="$red5"
    />
  )
}
```

### System Info

_No response_

### PR DESCRIPTION
**Pull request by TheEhsanSarshar**
fix #1985

### CODE REVIEW

**Comment by natew** [comment]
This feels a little weird, how does it fix the tag going away? Doesn't it just set the role? I would imagine with CSS driver the tag shouldn't go away, do you know why?

**Comment by TheEhsanSarshar** [comment]
@natew That's because createComponent uses an AnimatedView and react-native-web only translate role and accessibilityRole to corresponding tags

**Comment by TheEhsanSarshar** [comment]
interesting! with CSS driver tag goes away and `role` also has no effect

**Comment by natew** [comment]
With CSS driver we control the final element completely so `tag` should just work no?

**Pull request merged**
