### PR TITLE
upgrade lucide icons

### PR DESCRIPTION
**Pull request by dohomi**
This PR upgardes to `lucide-static@0.436.0`

### CODE REVIEW

**Comment by dohomi** [comment]
@natew could you have a look at this PR? Would love to get the latest icons from Lucide and just not sure if my PR does the right thing.

**Comment by dohomi** [comment]
@jonsherrard I miss some guidelines of doing it. I pulled the repo, updated lucide-static and just did following commands
```
yarn install
yarn generate
yarn build
```

shouldn't biome make sure its the same setup?

**Comment by natew** [comment]
I believe we have a `yarn lint:fix` command you can run, its possible the generate script doesnt run biome/right

**Comment by natew** [comment]
Got this done for you separately the other day but thanks for the pr

**Pull request closed without merging**
