### PR TITLE
Fix: Popover not working in Android

### PR DESCRIPTION
**Pull request by chakrihacker**
Closes https://github.com/tamagui/tamagui/issues/3029

### CODE REVIEW

**Comment by calvinxie668** [comment]
it's still not woking in android

**Comment by chakrihacker** [comment]
@calvinxie668 Tamagui picks from common js I think, so if you comment at source it will not work. You have to go to cjs folder I guess and comment it out. I don't remember the folder name, but commenting out one at a time helped me

@natew Can you please take a look at this Popper issues in Android and iOS please??

**Comment by devangsimplified** [comment]
Yes after commenting these lines it works on Android 👍

**Comment by devangpadhiyar** [comment]
Yes, After commenting the lines you have suggested it works on Android 👍

**Comment by khairul169** [comment]
Can confirm that commenting out these lines of code bring popover back to android in latest Expo SDK 52 👍 
[@tamagui__popper@1.116.14.patch](https://github.com/user-attachments/files/17757455/%40tamagui__popper%401.116.14.patch)

**Comment by natew** [comment]
Fix going out v1.116.15, had to clean up a few things so just merged it myself but appreciate you finding this out.

**Comment by hendrixgotcodes** [comment]
still not working on android

**Pull request closed without merging**
