### PR TITLE
chore: correct media query in examples

### PR DESCRIPTION
**Pull request by mzaien**
Hello 👋 , I saw this issue in the example and wanted to contribute back to the project

thanks for the amazing library

### CODE REVIEW

**Comment by natew** [comment]
Sorry this changes a bunch of very different files, what is this fixing?

**Comment by mzaien** [comment]
> Sorry this changes a bunch of very different files, what is this fixing?

changing `$xxs` to `$xs`

**Comment by natew** [comment]
What’s the reasoning?

**Comment by mzaien** [comment]
> What’s the reasoning?

When I tried the `xxs` from the progress demo , I had a type error that `xxs` is not a valid type

**Comment by natew** [comment]
Yea the docs are just an example, the site uses a different configuration.

**Pull request closed without merging**
