### PR TITLE
Update ButtonProps to support "value"

### LINKED ISSUE #252: [bug] allow property "value" on Button component
**Describe the bug**
Allow property "value" for `Button` component

**To Reproduce**

```ts
<Button value="list">list</Button
```

Currently this does not work / typescript breaks. But there are certain scenarios where the value of `<button>` needs to be defined.

### PR DESCRIPTION
**Pull request by dohomi**
add `value` to ButtonProps. closes #252 

@natew is that sufficient for making it work?

### CODE REVIEW

**Comment by dohomi** [comment]
@natew can you have a look at this small change? Integration of Quill requires the "value" prop on <button/>

**Comment by bang88** [comment]
IMO `Button·  should not have this prop. but you CAN extend from it.

**Comment by dohomi** [comment]
@bang88 Quill uses the value and its from the web point of view definitely a property which should be supported: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-value
For the native side I am not sure though..

**Comment by bang88** [comment]
The native side doesn't support this prop. We could define a custom Button with a value prop or create a Rich editor component in your package.

**Comment by dohomi** [comment]
Would it make sense to use Platform specific handler?

**Comment by bang88** [comment]
Not sure 😄

**Comment by natew** [comment]
I think yea in this case for now just fork button and add it for that use case, we need to sync with react native people to see what API they would want to make this work. Closing this but we can open an issue.

**Pull request closed without merging**
