### PR TITLE
open is any implicity

### PR DESCRIPTION
**Pull request by benschac**
when copy - pasta example ts error no implicit any

Didn't really wanna touch Accordion because it beta

### CODE REVIEW

**Comment by benschac** [comment]
* **#2491** <a href="https://app.graphite.dev/github/pr/tamagui/tamagui/2491?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @benschac and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by natew** [comment]
can't we fix the type on tamagui side?

**Comment by benschac** [comment]
Looked into it, but it's implicitly being passed / not obvious where the render function is defined.

I just wanted to help the user reading the docs copy-pasta'ing in the moment.

If you could point me to where the change is, I'd be happy to make it. (Spent roughly 15 minutes looking)

**Comment by natew** [comment]
Merged for now, we can revisit

**Pull request merged**
