### PR TITLE
update create template

### PR DESCRIPTION
**Pull request by benschac**
@natew is going to take this one over

### CODE REVIEW

**Comment by benschac** [comment]
@natew or @alitnk - could either of you try running tests on your local machine.

I'm having a hard time groking why this test is failing locally.

**Comment by benschac** [comment]
command runs as expected locally and creates starter as expected.

@natew - what's next step for `starters`/`nextexposolito`?

rm -rf it from monorepo and update the docs?

**Comment by natew** [comment]
@benschac we should have a way for the release script to update the external repo as part of this change for sure. even if it just looks locally at a dir you specify.

**Comment by natew** [comment]
this has been implemented

**Pull request closed without merging**
