### PR TITLE
@tamagui/popover platform specific files

### LINKED ISSUE #688: [bug] @tamagui/popover seems to be bundling react-dom on native
## **Describe the bug**
Trying to implement `tamagui` on a vanilla React Native project (no web)

`@tamagui/popover` seems to be bundling `react-dom` on native

## **To Reproduce**
1. `npx react-native init`
2. Add `tamagui` according to docs.

Here's a reproduction repository with all the commits following the docs: https://github.com/criszz77/tamagui-bugs
<br />
image

## Solution

PR: https://github.com/tamagui/tamagui/pull/689

After applying the patch the app runs with warnings:

### `react-native-web` and `react-dom` not found warnings on native

This is probably unrelated and should have its own issue. 

image

### PR DESCRIPTION
**Pull request by criszz77**
Should fix #688 

It seems to be working, but I can't say I'm happy with the changes.

### CODE REVIEW

**Comment by natew** [comment]
How about making just the hook to get the context in its own file, keep the wrapper in the same file so it doesn't diverge?

**Comment by criszz77** [comment]
Perfect, will do tbose changes later today

**Comment by criszz77** [comment]
I believe it looks better, hope I didn't miss anything. Cheers 🍻

**Comment by natew** [comment]
thanks a bunch for this!

**Comment by criszz77** [comment]
Thank you as well!

**Pull request merged**
