### PR TITLE
feat: Add TypeScript support for `type: 'timing'`

### PR DESCRIPTION
**Pull request by nandorojo**

### CODE REVIEW

**Comment by nandorojo** [comment]
## `type: timing`

Screen Shot 2022-12-20 at 12 40 45 PM

## Default to `type: spring`

Screen Shot 2022-12-20 at 12 40 54 PM

## `type: spring`

Screen Shot 2022-12-20 at 12 41 26 PM

**Comment by natew** [comment]
If you can conventional commit this with `feat`... I'll need to test timing animations actually works across drivers too.

**Comment by nandorojo** [comment]
Oh right forgot the commita

**Comment by nandorojo** [comment]
Do commits themselves need the comment, or just the PR?

**Comment by natew** [comment]
Commits themselves

**Comment by natew** [comment]
Cherry picked onto another branch and made a change to switch to timing based instead of spring in logic:

https://github.com/tamagui/tamagui/pull/562

**Pull request closed without merging**
