### PR TITLE
Fix: Remove Kanye from landing page

### PR DESCRIPTION
**Pull request by jlalmes**

### CODE REVIEW

**Comment by jonsherrard** [comment]
Putin & Assad apologist Roger Water's most famous work in place? Also 👎

**Comment by jlalmes** [comment]
Fair enough, should probably be changed to something though

**Comment by jonsherrard** [comment]
https://open.spotify.com/album/6KJ8oH9XV1UqTPwU4jCiiV?si=TFZo1fEGQpSq1-UtL9zyUA

My submission: 

image

**Comment by natew** [comment]
Fixed in https://github.com/tamagui/tamagui/pull/438

**Pull request closed without merging**
