### PR TITLE
update docs kitchen sink web

### PR DESCRIPTION
**Pull request by benschac**
was trying to test skeleton demo in web, wasn't really documented. Also, required expo web package.

Additionally tried:

- `http://localhost:19006/?test=LinearGradient`
- `http://localhost:19006/?kitchen=LinearGradient`

but nothing was rendering / error. If those links work, could you leave an example? I'll update the docs some more with examples

### CODE REVIEW

**Comment by benschac** [comment]
Current dependencies on/for this PR:
* master
  * **PR #1906** <a href="https://app.graphite.dev/github/pr/tamagui/tamagui/1906?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/tamagui/tamagui/1906?utm_source=stack-comment).

**Comment by natew** [comment]
`yarn sandbox` should do it, maybe linear gradient breaks but ?demo and ?test work there

**Review by natew — COMMENTED** [review]
yarn.lock change probably accidental

**Comment by natew** [comment]
`yarn sandbox` is how you run kitchen-sink web actually, it's sort of a legacy naming thing.

**Pull request closed without merging**
