### PR TITLE
update button blog post

### PR DESCRIPTION
**Pull request by benschac**
did a copy pasta from the docs. Cost me 20 minutes hunting down the issue. Assuming other folks will find this helpful.

Not really sure where exactly this belongs? Would be helpful if there was a recommended `tsconfig` in the manual setup docs.

### CODE REVIEW

**Comment by natew** [comment]
yo! sorry i let this sit, it needs a rebase!

**Comment by benschac** [comment]
@natew - rebased 🙏🏻

**Comment by benschac** [comment]
@natew - looking good?

**Comment by natew** [comment]
@benschac thank you

**Pull request merged**
