### PR TITLE
refact: move addTheme, updateTheme to @tamagui/load-theme package 

### PR DESCRIPTION
**Pull request by TheEhsanSarshar**
- [x] LGTM

### CODE REVIEW

**Comment by TheEhsanSarshar** [comment]
I think we need to rename `@tamagui/add-font` to `@tamagui/load-font` as well.

**Comment by TheEhsanSarshar** [comment]
Right now I marked `addTheme` and `loadTheme` as deprecated. and also this new package `@tamagui/load-theme` is not accessible in `tamagui` because of naming conflicts.
we should remove those deprecated functions first ( maybe in a minor version ), and then add this new package in tamagui namespace

**Comment by natew** [comment]
I sort of like `add` better than `load` because in the future we can add `remove` which is more symmetrical.

**Comment by TheEhsanSarshar** [comment]
you mean this ?
`import { addTheme, updateTheme,  removeTheme } from '@tamagui/add-theme'`

the only reason that changed the name from `add-font` to `load-font` was having those extra functions

**Comment by natew** [comment]
Ah yea technically it's generic... maybe we can do `@tamagui/theme`. That's kind of nice. Same for `@tamagui/font`. Thinking if there's some other overlap but I think it's fine.

**Comment by TheEhsanSarshar** [comment]
@natew both packages are renamed to `@tamagui/font` and `@tamagui/theme`

**Comment by natew** [comment]
Hey @TheEhsanSarshar thanks so much for this, I can fix these conflicts but if you get time to would be great and I'll hit merge.

**Comment by TheEhsanSarshar** [comment]
@natew it's done

**Pull request merged**
