### PR TITLE
[issue] style inconsistency in production

### PR DESCRIPTION
**Pull request by ebg1223**
To reproduce:
cd starters/next-expo-solito
yarn
yarn build && yarn web:prod && yarn web:prod:serve

Open the page. Click the button on home screen and you are redirected to a page with 3 buttons, but at the top of the window. 

Refresh the page, and it renders correctly in the center of the window.

See screenshots folder in the starter for example.

### CODE REVIEW

**Comment by ebg1223** [comment]
I believe it has something to do with alignItems={"center"} on the YStack on the homescreen. Without setting this, rendering is normal.

**Comment by ebg1223** [comment]
After some more testing, it seems like the issue has to do with how style props are passed from parent to child component when static rendered next-js vs. how they are rendered client-side. I have some more examples of some idiosyncrasies between the 2 versions.

**Comment by natew** [comment]
@ebg1223 thanks for the detailed write up, I'll take a look at this soon.

**Comment by ebg1223** [comment]
@natew thank you!!

**Comment by natew** [comment]
This should be fixed on latest, lmk

**Pull request closed without merging**
